### ISSUE TITLE
Fix useEffect loops and double loading

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomap_en2b#123] opened 2023-04-25 10:04 UTC

**Comment by jjgancfer** [comment] 2023-04-29 15:12
I think I found the cause. When using the _useEffect_ hook with dependencies, React executes the function when any dependency changes. As we had assigned to it many dependencies, the function was executed every time a single one changed. The refactor in #130 incorporated a major rework of the landmark retrieval, so now it should be fixed.

**Closed by jjgancfer** 2023-04-29 15:12 UTC
Labels: bug :gear:
